[application]
asset_dir = "public"
[web.app]
base_path="typecrab"

# HTML title tag content
title = "typecrab"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
